version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

conda:
  environment: ci/requirements-docs.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false
